#define ANSI_COLOR_RED                				"\x1b[31m"
#define ANSI_COLOR_GREEN              				"\x1b[32m"
#define ANSI_COLOR_YELLOW             				"\x1b[33m"
#define ANSI_COLOR_BLUE               				"\x1b[34m"
#define ANSI_COLOR_BLUE_UNDERLINED    				"\e[4m \x1b[34m"
#define ANSI_COLOR_BLUE_BOLD          				"\e[1m \x1b[34m"
#define ANSI_COLOR_MAGENTA               			"\e[95m"
#define ANSI_COLOR_MAGENTA_LIGHT               			"\e[95m"
#define ANSI_COLOR_MAGENTA_BG               			"\e[45m"
#define ANSI_COLOR_MAGENTA_UNDERLINED    			"\e[4m \x1b[95m"
#define ANSI_COLOR_MAGENTA_BOLD          			"\e[1m \x1b[35m"
#define ANSI_COLOR_CYAN               				"\x1b[36m"
#define ANSI_COLOR_CYAN_LIGHT              			"\x1b[96m"
#define ANSI_COLOR_CYAN_LIGHT_BOLD               		"\e[1m \x1b[96m"
#define ANSI_COLOR_CYAN_BG               			"\e[46m"
#define ANSI_COLOR_CYAN_UNDERLINED_BG               		"\e[4m \e[46m"


#define ANSI_COLOR_CYAN_UNDERLINED    				"\e[4m \x1b[36m"
#define ANSI_COLOR_CYAN_BOLD          				"\e[1m \x1b[36m"

#define ANSI_COLOR_AAA     					"\e[1m34m"
// #define ANSI_COLOR_BBB     					"\x1b[38m"
#define ANSI_COLOR_RESET   					"\x1b[0m"
